apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: application
spec:
  selector:
    matchLabels:
      run: web-app
  replicas: 2
  template:
    metadata:
      labels:
        run: web-app
    spec:
      containers:
      - name: web-app
        image: localhost:5000/web-app
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: application
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
    targetPort: 9999
  selector:
    run: web-app
  sessionAffinity: None
  type: NodePort
